[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
#build_info=true
#extra_output=["storageLayout"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


[fuzz]
runs = 200

[invariant]
runs = 200
depth = 50
fail_on_revert = false
